version: '3'

vars:
  GOOS: "{{default OS .GOOS}}"
  MVNW: '{{if eq .GOOS "windows"}}mvnw.cmd{{else}}./mvnw{{end}}'
  SLEEP_CMD: '{{if eq .GOOS "windows"}}timeout{{else}}sleep{{end}}'
  IMAGE_NAME: 'sivaprasadreddy/spring-modular-monolith'
  DC_FILE: "compose.yml"

tasks:
  default:
    cmds:
      - task: test
  test:
    deps: [ format ]
    cmds:
      - "{{.MVNW}} clean verify"

  format:
    cmds:
      - "{{.MVNW}} spotless:apply"

  build_image:
    cmds:
      - "{{.MVNW}} clean compile spring-boot:build-image -DskipTests -DdockerImageName={{.IMAGE_NAME}}"

  start:
    deps: [ build_image ]
    cmds:
      - docker compose --profile app -f "{{.DC_FILE}}" up --force-recreate -d

  stop:
    cmds:
      - docker compose --profile app -f "{{.DC_FILE}}" stop
      - docker compose --profile app -f "{{.DC_FILE}}" rm -f

  restart:
    cmds:
      - task: stop
      - task: sleep
      - task: start

  kind_create:
    deps: [ build_image ]
    cmds:
      - '{{if eq .GOOS "windows"}}powershell -NoProfile -ExecutionPolicy Bypass -File ./k8s/kind/kind-cluster.ps1 create{{else}}./k8s/kind/kind-cluster.sh create{{end}}'

  kind_create_force:
    desc: "Create kind cluster and force hostPort mappings (no build/test)"
    deps: [ build_image ]
    cmds:
      - '{{if eq .GOOS "windows"}}powershell -NoProfile -ExecutionPolicy Bypass -File ./k8s/kind/kind-cluster.ps1 --force-hostports create{{else}}./k8s/kind/kind-cluster.sh --force-hostports create{{end}}'

  kind_destroy:
    cmds:
      - '{{if eq .GOOS "windows"}}powershell -NoProfile -ExecutionPolicy Bypass -File ./k8s/kind/kind-cluster.ps1 destroy{{else}}./k8s/kind/kind-cluster.sh destroy{{end}}'

  k8s_deploy:
    cmds:
      - kind load docker-image sivaprasadreddy/spring-modular-monolith --name sivalabs-k8s
      - kubectl apply -f k8s/manifests/

  k8s_undeploy:
    cmds:
      - kubectl delete -f k8s/manifests/

  sleep:
    vars:
      DURATION: "{{default 5 .DURATION}}"
    cmds:
      - "{{.SLEEP_CMD}} {{.DURATION}}"
