apiVersion: v1
kind: Service
metadata:
  name: spring-modular-monolith-postgres-svc
spec:
  selector:
    app: spring-modular-monolith-postgres-pod
  ports:
    - port: 5432
      targetPort: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-modular-monolith-postgres-deployment
spec:
  selector:
    matchLabels:
      app: spring-modular-monolith-postgres-pod
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: spring-modular-monolith-postgres-pod
    spec:
      containers:
        - name: postgres
          image: "postgres:17-alpine"
          ports:
            - name: postgres
              containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POSTGRES_DB
              value: postgres
