apiVersion: v1
kind: Service
metadata:
  name: spring-modular-monolith-rabbitmq-svc
spec:
  type: NodePort
  selector:
    app: spring-modular-monolith-rabbitmq-pod
  ports:
    - name: rabbitmq-port-mapping
      port: 5672
      targetPort: 5672
      protocol: TCP
    - name: rabbitmq--gui-port-mapping
      port: 15672
      targetPort: 15672
      protocol: TCP
      nodePort: 30091
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-modular-monolith-rabbitmq-deployment
spec:
  selector:
    matchLabels:
      app: spring-modular-monolith-rabbitmq-pod
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: spring-modular-monolith-rabbitmq-pod
    spec:
      containers:
        - name: rabbitmq
          image: "rabbitmq:4.1.4-management"
          ports:
            - name: rabbitmq
              containerPort: 5672
            - name: rabbitmq-admin
              containerPort: 15672
          env:
            - name: RABBITMQ_DEFAULT_USER
              value: guest
            - name: RABBITMQ_DEFAULT_PASS
              value: guest

